# Copyright 2022 tink <qietingfy@gmail.com>. All rights reserved.
# Use of this source code is governed by a MIT style
# license that can be found in the LICENSE file.

run:
  timeout: 10m
linters:
  disable-all: true
  enable:
    - misspell
    - ineffassign
    - typecheck
    - varcheck
    - unused
    - structcheck
    - deadcode
    - gosimple
    - goimports
    - errcheck
    - staticcheck
    - stylecheck
    - gosec
    - asciicheck
    - bodyclose
    - exportloopref
    - rowserrcheck
    - unconvert
    - makezero
    - durationcheck
    - prealloc
    - predeclared
    - govet
    - dogsled
    - sqlclosecheck
    - whitespace

linters-settings:
  staticcheck:
    checks: ["S1002","S1004","S1007","S1009","S1010","S1012","S1019","S1020","S1021","S1024","S1030","SA2*","SA3*","SA4009","SA5*","SA6000","SA6001","SA6005", "-SA2002"]
  stylecheck:
    checks: ["-ST1003"]
  gosec:
    severity: "low"
    confidence: "low"
    excludes:
      - G101
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - rowserrcheck
        - makezero
